user_user_user:
    resource: "@UserUserBundle/Resources/config/routes/user.yml"
    prefix:   /user

task_task_task:
    resource: "@UserUserBundle/Resources/config/routes/task.yml"
    prefix:   /task