<?php

namespace Ubicacion\UbicacionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommunesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunesRepository extends EntityRepository
{
}
