<?php

namespace Ubicacion\UbicacionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProvincesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvincesRepository extends EntityRepository
{
}
