ubicacion:
    resource: "@UbicacionBundle/Resources/config/routing.yml"
    prefix:   /

user_user:
    resource: "@UserUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#Autentication

user_user_homepage:
    path:     /
    defaults: { _controller: UserUserBundle:User:home }
    
user_user_login:
    path:     /login
    defaults: { _controller: UserUserBundle:Security:login }
    
user_user_login_check:
    path:     /login_check
    defaults: { _controller: UserUserBundle:Security:loginCheck }

user_user_logout:
    path:     /logout   